import type { Meta, StoryObj } from "@storybook/react";

import { Button } from "@kuzenbo/core/ui/button";

import { CodeBlockToolbar } from "../code-block-toolbar";

const ROUTE_SNIPPET = `export async function GET() {
  return Response.json({ healthy: true });
}`;

const meta = {
  title: "Code/CodeBlockToolbar/Default",
  component: CodeBlockToolbar,
  tags: ["autodocs"],
  args: {
    copyValue: ROUTE_SNIPPET,
    language: "ts",
    title: "apps/website/app/api/health/route.ts",
  },
} satisfies Meta<typeof CodeBlockToolbar>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};

export const PathAwareToolbar: Story = {
  args: {
    start: ({ language }) => (
      <div className="flex min-w-0 items-center gap-2">
        <span className="inline-flex items-center rounded-md border border-border bg-muted/40 px-2 py-0.5 font-mono text-xs text-muted-foreground">
          {language}
        </span>
        <span className="truncate text-xs text-muted-foreground">
          packages/code/src/ui/code-preview/code-preview.tsx
        </span>
      </div>
    ),
  },
};

export const WithCustomCopyAction: Story = {
  args: {
    title: "release.yml",
    copyValue: `name: Release\n\non:\n  workflow_dispatch:`,
    end: ({ copy }) => (
      <Button
        onClick={() => {
          copy();
        }}
        size="xs"
        type="button"
        variant="outline"
      >
        Copy workflow
      </Button>
    ),
  },
};

export const ReadOnlySnippetToolbar: Story = {
  args: {
    copyValue: undefined,
    title: "Generated by schema compiler",
    end: (
      <span className="inline-flex items-center rounded-md border border-border bg-muted/40 px-2 py-0.5 text-xs text-muted-foreground">
        Read-only
      </span>
    ),
  },
};
