import {
  AreaChart,
  BarChart,
  BubbleChart,
  CompositeChart,
  DonutChart,
  FunnelChart,
  Heatmap,
  LineChart,
  PieChart,
  RadarChart,
  RadialBarChart,
  ScatterChart,
  Sparkline,
} from "../prebuilt";
import {
  ChartAutoSize,
  ChartFrame,
  Chart as PrimitiveChart,
  ChartLegend,
  ChartLegendContent,
  ChartPortalTarget,
  ChartProvider,
  ChartRoot,
  ChartStyle,
  ChartTooltip,
  ChartTooltipContent,
  useActiveTooltipCoordinate,
  useActiveTooltipDataPoints,
  useActiveTooltipLabel,
  useChart,
  useChartConfig,
  useChartHeight,
  useChartPortalTarget,
  useChartWidth,
  useIsTooltipActive,
  useOffset,
  usePlotArea,
  useSeriesColor,
  useSeriesColorVar,
} from "../primitives/chart";

const Chart = Object.assign(PrimitiveChart, {
  Preset: {
    Area: AreaChart,
    Bubble: BubbleChart,
    Line: LineChart,
    Bar: BarChart,
    Composite: CompositeChart,
    Donut: DonutChart,
    Funnel: FunnelChart,
    Heatmap,
    Pie: PieChart,
    Radar: RadarChart,
    RadialBar: RadialBarChart,
    Scatter: ScatterChart,
    Sparkline,
  },
});

export {
  AreaChart,
  BarChart,
  BubbleChart,
  Chart,
  ChartAutoSize,
  ChartFrame,
  ChartLegend,
  ChartLegendContent,
  ChartPortalTarget,
  ChartProvider,
  ChartRoot,
  ChartStyle,
  ChartTooltip,
  ChartTooltipContent,
  CompositeChart,
  DonutChart,
  FunnelChart,
  Heatmap,
  LineChart,
  PieChart,
  RadarChart,
  RadialBarChart,
  ScatterChart,
  Sparkline,
  useChart,
  useActiveTooltipCoordinate,
  useActiveTooltipDataPoints,
  useActiveTooltipLabel,
  useChartConfig,
  useChartHeight,
  useChartWidth,
  useIsTooltipActive,
  useOffset,
  usePlotArea,
  useSeriesColor,
  useSeriesColorVar,
  useChartPortalTarget,
};

export type {
  AreaChartGradientStop,
  AreaChartProps,
  AreaChartType,
  BarChartProps,
  BarChartType,
  BubbleChartDatum,
  BubbleChartProps,
  BubbleChartSeries,
  ChartReferenceLine,
  CompositeChartProps,
  CompleteCartesianChartBaseProps,
  CompleteChartCurveType,
  CompleteChartDatum,
  CompleteChartSeries,
  CompleteCompositeSeries,
  DonutCenterLabelContext,
  DonutChartProps,
  FunnelChartProps,
  FunnelLabelPosition,
  HeatmapCellRuntime,
  HeatmapProps,
  LineChartGradientStop,
  LineChartProps,
  LineChartType,
  PieChartProps,
  RadarChartProps,
  RadarSeriesProps,
  RadialBarChartProps,
  RadialBarLabelPosition,
  RadialBarSeriesProps,
  ScatterChartDatum,
  ScatterChartProps,
  ScatterChartSeries,
  SparklineGradientStop,
  SparklineProps,
  SparklineRuntimeSeries,
  SparklineTrendColors,
  SparklineTrendDirection,
} from "../prebuilt";

export type {
  ChartAutoSizeProps,
  ChartProps,
  ChartConfig,
  ChartFrameProps,
  ChartLegendProps,
  ChartLegendContentProps,
  ChartProviderProps,
  ChartPortalTargetProps,
  ChartRootProps,
  ChartStyleProps,
  ChartTooltipProps,
  ChartTooltipContentProps,
  UseChartPortalTargetResult,
} from "../primitives/chart";
