const lines = [
  "Kuzenbo release commands",
  "",
  "Required conventions:",
  "- Use a two-channel release model: `next` (prerelease) and `stable`.",
  "- Channel-to-branch policy is strict: next->main, stable->main.",
  "- Channel is always explicit (`next`, `stable`).",
  "- All packages in `packages/*` must stay lockstep.",
  "- Real publishing happens only in GitHub Actions trusted publishing workflow.",
  "- Release artifacts are packed with `bun pm pack`, manifest entrypoints are validated against tarball files, and then tarballs are published via npm provenance.",
  "",
  "Commands:",
  "- bun run release:status",
  "- bun run release:changeset -- --bump <patch|minor|major> --channel <channel> --summary <text>",
  "- bun run release:notes -- --version <version> --channel <channel>",
  "- bun run release:validate -- --version <version> --channel <channel> [--ref <main>]",
  "- bun run release:dry-run -- --version <version> --channel <channel> [--ref <main>]",
  "- bun run changeset:pre:enter -- <alpha|beta|rc|next>",
  "- bun run changeset:pre:exit",
  "- bun run changeset:version",
  "",
  "Publishing:",
  "- Use `.github/workflows/release.yml` with workflow_dispatch.",
  "- Workflow `ref` input accepts only `main`.",
  "- Confirm phrase format: `release-<version>-<channel>`.",
  "- Workflow input `publish_mode` supports `normal` and dedicated `recovery` mode.",
  "",
];

console.log(lines.join("\n"));
