name: Bug Report
description: Report a reproducible bug in Kuzenbo
title: "[Bug]: "
labels:
  - bug
  - triage
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug report. Please include enough detail for us to reproduce the issue quickly.

  - type: dropdown
    id: affected-area
    attributes:
      label: Affected Area
      description: Where did you encounter the issue?
      options:
        - "@kuzenbo/ai"
        - "@kuzenbo/charts"
        - "@kuzenbo/core"
        - "@kuzenbo/datatable"
        - "@kuzenbo/date"
        - "@kuzenbo/hooks"
        - "@kuzenbo/notifications"
        - "@kuzenbo/cli"
        - "@kuzenbo/mcp"
        - "apps/website"
        - "storybook (package-local)"
        - "docs"
        - "other"
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: Briefly describe the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Reproduction Steps
      description: Share exact steps to reproduce the issue.
      placeholder: |
        1. Run ...
        2. Open ...
        3. Click ...
        4. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Share environment details to help us reproduce.
      placeholder: |
        - OS:
        - Node:
        - Bun:
        - Package version(s):
        - Browser (if relevant):

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add screenshots, logs, stack traces, or links.

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues before creating this report.
          required: true
        - label: I can reproduce this issue with current repository code.
          required: true
        - label: This is not a security vulnerability report.
          required: true
