import { defineConfig } from "tsdown";

export default defineConfig({
  attw: {
    ignoreRules: ["no-resolution"],
    profile: "esm-only",
  },
  clean: true,
  dts: {
    sourcemap: true,
  },
  entry: {
    index: "src/index.ts",
    "use-click-outside": "src/use-click-outside/use-click-outside.ts",
    "use-clipboard": "src/use-clipboard/use-clipboard.ts",
    "use-collapse": "src/use-collapse/use-collapse.ts",
    "use-color-scheme": "src/use-color-scheme/use-color-scheme.ts",
    "use-counter": "src/use-counter/use-counter.ts",
    "use-debounced-callback":
      "src/use-debounced-callback/use-debounced-callback.ts",
    "use-debounced-state": "src/use-debounced-state/use-debounced-state.ts",
    "use-debounced-value": "src/use-debounced-value/use-debounced-value.ts",
    "use-did-update": "src/use-did-update/use-did-update.ts",
    "use-disclosure": "src/use-disclosure/use-disclosure.ts",
    "use-document-title": "src/use-document-title/use-document-title.ts",
    "use-document-visibility":
      "src/use-document-visibility/use-document-visibility.ts",
    "use-event-listener": "src/use-event-listener/use-event-listener.ts",
    "use-eye-dropper": "src/use-eye-dropper/use-eye-dropper.ts",
    "use-favicon": "src/use-favicon/use-favicon.ts",
    "use-fetch": "src/use-fetch/use-fetch.ts",
    "use-file-dialog": "src/use-file-dialog/use-file-dialog.ts",
    "use-floating-window": "src/use-floating-window/use-floating-window.ts",
    "use-focus-return": "src/use-focus-return/use-focus-return.ts",
    "use-focus-trap": "src/use-focus-trap/use-focus-trap.ts",
    "use-focus-within": "src/use-focus-within/use-focus-within.ts",
    "use-force-update": "src/use-force-update/use-force-update.ts",
    "use-fullscreen": "src/use-fullscreen/use-fullscreen.ts",
    "use-hash": "src/use-hash/use-hash.ts",
    "use-headroom": "src/use-headroom/use-headroom.ts",
    "use-horizontal-collapse": "src/use-collapse/use-horizontal-collapse.ts",
    "use-hotkeys": "src/use-hotkeys/use-hotkeys.ts",
    "use-hover": "src/use-hover/use-hover.ts",
    "use-id": "src/use-id/use-id.ts",
    "use-idle": "src/use-idle/use-idle.ts",
    "use-in-viewport": "src/use-in-viewport/use-in-viewport.ts",
    "use-input-state": "src/use-input-state/use-input-state.ts",
    "use-intersection": "src/use-intersection/use-intersection.ts",
    "use-interval": "src/use-interval/use-interval.ts",
    "use-is-first-render": "src/use-is-first-render/use-is-first-render.ts",
    "use-isomorphic-effect":
      "src/use-isomorphic-effect/use-isomorphic-effect.ts",
    "use-list-state": "src/use-list-state/use-list-state.ts",
    "use-local-storage": "src/use-local-storage/use-local-storage.ts",
    "use-logger": "src/use-logger/use-logger.ts",
    "use-long-press": "src/use-long-press/use-long-press.ts",
    "use-map": "src/use-map/use-map.ts",
    "use-media-query": "src/use-media-query/use-media-query.ts",
    "use-merged-ref": "src/use-merged-ref/use-merged-ref.ts",
    "use-mobile": "src/use-mobile/use-mobile.ts",
    "use-mounted": "src/use-mounted/use-mounted.ts",
    "use-mouse": "src/use-mouse/use-mouse.ts",
    "use-move": "src/use-move/use-move.ts",
    "use-mutation-observer":
      "src/use-mutation-observer/use-mutation-observer.ts",
    "use-network": "src/use-network/use-network.ts",
    "use-orientation": "src/use-orientation/use-orientation.ts",
    "use-os": "src/use-os/use-os.ts",
    "use-page-leave": "src/use-page-leave/use-page-leave.ts",
    "use-pagination": "src/use-pagination/use-pagination.ts",
    "use-previous": "src/use-previous/use-previous.ts",
    "use-queue": "src/use-queue/use-queue.ts",
    "use-radial-move": "src/use-radial-move/use-radial-move.ts",
    "use-reduced-motion": "src/use-reduced-motion/use-reduced-motion.ts",
    "use-resize-observer": "src/use-resize-observer/use-resize-observer.ts",
    "use-scroll-into-view": "src/use-scroll-into-view/use-scroll-into-view.ts",
    "use-scroll-spy": "src/use-scroll-spy/use-scroll-spy.ts",
    "use-scroller": "src/use-scroller/use-scroller.ts",
    "use-selection": "src/use-selection/use-selection.ts",
    "use-session-storage": "src/use-session-storage/use-session-storage.ts",
    "use-set": "src/use-set/use-set.ts",
    "use-set-state": "src/use-set-state/use-set-state.ts",
    "use-shallow-effect": "src/use-shallow-effect/use-shallow-effect.ts",
    "use-state-history": "src/use-state-history/use-state-history.ts",
    "use-text-selection": "src/use-text-selection/use-text-selection.ts",
    "use-throttled-callback":
      "src/use-throttled-callback/use-throttled-callback.ts",
    "use-throttled-state": "src/use-throttled-state/use-throttled-state.ts",
    "use-throttled-value": "src/use-throttled-value/use-throttled-value.ts",
    "use-timeout": "src/use-timeout/use-timeout.ts",
    "use-toggle": "src/use-toggle/use-toggle.ts",
    "use-uncontrolled": "src/use-uncontrolled/use-uncontrolled.ts",
    "use-validated-state": "src/use-validated-state/use-validated-state.ts",
    "use-viewport-size": "src/use-viewport-size/use-viewport-size.ts",
    "use-window-event": "src/use-window-event/use-window-event.ts",
    "use-window-scroll": "src/use-window-scroll/use-window-scroll.ts",
  },
  exports: {
    devExports: true,
    packageJson: true,
  },
  format: ["esm"],
  platform: "browser",
  publint: true,
  sourcemap: true,
});
