import { defineConfig } from "tsdown";

export default defineConfig({
  attw: {
    ignoreRules: ["no-resolution"],
    profile: "esm-only",
  },
  clean: true,
  dts: {
    sourcemap: true,
  },
  entry: {
    provider: "src/provider/index.ts",
    size: "src/size/index.ts",
    "ui/accordion": "src/ui/accordion/accordion.tsx",
    "ui/affix": "src/ui/affix/affix.tsx",
    "ui/alert": "src/ui/alert/alert.tsx",
    "ui/alert-dialog": "src/ui/alert-dialog/alert-dialog.tsx",
    "ui/announcement": "src/ui/announcement/announcement.tsx",
    "ui/aspect-ratio": "src/ui/aspect-ratio/aspect-ratio.tsx",
    "ui/autocomplete": "src/ui/autocomplete/autocomplete.tsx",
    "ui/avatar": "src/ui/avatar/avatar.tsx",
    "ui/badge": "src/ui/badge/badge.tsx",
    "ui/breadcrumb": "src/ui/breadcrumb/breadcrumb.tsx",
    "ui/button": "src/ui/button/button.tsx",
    "ui/button-group": "src/ui/button-group/button-group.tsx",
    "ui/card": "src/ui/card/card.tsx",
    "ui/carousel": "src/ui/carousel/carousel.tsx",
    "ui/checkbox": "src/ui/checkbox/checkbox.tsx",
    "ui/checkbox-group": "src/ui/checkbox-group/checkbox-group.tsx",
    "ui/code": "src/ui/code/code.tsx",
    "ui/collapsible": "src/ui/collapsible/collapsible.tsx",
    "ui/combobox": "src/ui/combobox/combobox.tsx",
    "ui/command": "src/ui/command/command.tsx",
    "ui/container": "src/ui/container/container.tsx",
    "ui/context-menu": "src/ui/context-menu/context-menu.tsx",
    "ui/copy-button": "src/ui/copy-button/copy-button.tsx",
    "ui/dialog": "src/ui/dialog/dialog.tsx",
    "ui/drawer": "src/ui/drawer/drawer.tsx",
    "ui/dropdown-menu": "src/ui/dropdown-menu/dropdown-menu.tsx",
    "ui/dropzone": "src/ui/dropzone/dropzone.tsx",
    "ui/emoji-picker": "src/ui/emoji-picker/emoji-picker.tsx",
    "ui/empty": "src/ui/empty/empty.tsx",
    "ui/field": "src/ui/field/field.tsx",
    "ui/fieldset": "src/ui/fieldset/fieldset.tsx",
    "ui/form": "src/ui/form/form.tsx",
    "ui/input": "src/ui/input/input.tsx",
    "ui/input-group": "src/ui/input-group/input-group.tsx",
    "ui/input-otp": "src/ui/input-otp/input-otp.tsx",
    "ui/item": "src/ui/item/item.tsx",
    "ui/kbd": "src/ui/kbd/kbd.tsx",
    "ui/label": "src/ui/label/label.tsx",
    "ui/marquee": "src/ui/marquee/marquee.tsx",
    "ui/menubar": "src/ui/menubar/menubar.tsx",
    "ui/meter": "src/ui/meter/meter.tsx",
    "ui/navigation-list": "src/ui/navigation-list/navigation-list.tsx",
    "ui/navigation-menu": "src/ui/navigation-menu/navigation-menu.tsx",
    "ui/number-field": "src/ui/number-field/number-field.tsx",
    "ui/pagination": "src/ui/pagination/pagination.tsx",
    "ui/pill": "src/ui/pill/pill.tsx",
    "ui/popover": "src/ui/popover/popover.tsx",
    "ui/portal": "src/ui/portal/portal.tsx",
    "ui/preview-card": "src/ui/preview-card/preview-card.tsx",
    "ui/progress": "src/ui/progress/progress.tsx",
    "ui/qr-code": "src/ui/qr-code/qr-code.tsx",
    "ui/radio-group": "src/ui/radio-group/radio-group.tsx",
    "ui/range-slider": "src/ui/range-slider/range-slider.tsx",
    "ui/range-slider/range-slider-types":
      "src/ui/range-slider/range-slider-types.ts",
    "ui/rating": "src/ui/rating/rating.tsx",
    "ui/resizable": "src/ui/resizable/resizable.tsx",
    "ui/scroll-area": "src/ui/scroll-area/scroll-area.tsx",
    "ui/select": "src/ui/select/select.tsx",
    "ui/separator": "src/ui/separator/separator.tsx",
    "ui/sheet": "src/ui/sheet/sheet.tsx",
    "ui/sidebar": "src/ui/sidebar/sidebar.tsx",
    "ui/skeleton": "src/ui/skeleton/skeleton.tsx",
    "ui/slider": "src/ui/slider/slider.tsx",
    "ui/spacer": "src/ui/spacer/spacer.tsx",
    "ui/spinner": "src/ui/spinner/spinner.tsx",
    "ui/switch": "src/ui/switch/switch.tsx",
    "ui/table": "src/ui/table/table.tsx",
    "ui/tabs": "src/ui/tabs/tabs.tsx",
    "ui/textarea": "src/ui/textarea/textarea.tsx",
    "ui/theme-icon": "src/ui/theme-icon/theme-icon.tsx",
    "ui/timeline": "src/ui/timeline/timeline.tsx",
    "ui/toggle": "src/ui/toggle/toggle.tsx",
    "ui/toggle-group": "src/ui/toggle-group/toggle-group.tsx",
    "ui/toolbar": "src/ui/toolbar/toolbar.tsx",
    "ui/tooltip": "src/ui/tooltip/tooltip.tsx",
    "ui/typography": "src/ui/typography/typography.tsx",
  },
  exports: {
    devExports: true,
    packageJson: true,
  },
  format: ["esm"],
  platform: "neutral",
  publint: true,
  sourcemap: true,
});
