import type { TsdownInputOption } from "tsdown";

import { defineConfig } from "tsdown";

const entries: TsdownInputOption = {
  index: "src/index.ts",
  accordion: "src/ui/accordion/accordion.tsx",
  affix: "src/ui/affix/affix.tsx",
  alert: "src/ui/alert/alert.tsx",
  "alert-dialog": "src/ui/alert-dialog/alert-dialog.tsx",
  announcement: "src/ui/announcement/announcement.tsx",
  "aspect-ratio": "src/ui/aspect-ratio/aspect-ratio.tsx",
  autocomplete: "src/ui/autocomplete/autocomplete.tsx",
  avatar: "src/ui/avatar/avatar.tsx",
  badge: "src/ui/badge/badge.tsx",
  breadcrumb: "src/ui/breadcrumb/breadcrumb.tsx",
  button: "src/ui/button/button.tsx",
  "button-group": "src/ui/button-group/button-group.tsx",
  card: "src/ui/card/card.tsx",
  carousel: "src/ui/carousel/carousel.tsx",
  checkbox: "src/ui/checkbox/checkbox.tsx",
  "checkbox-group": "src/ui/checkbox-group/checkbox-group.tsx",
  collapsible: "src/ui/collapsible/collapsible.tsx",
  combobox: "src/ui/combobox/combobox.tsx",
  code: "src/ui/code/code.tsx",
  container: "src/ui/container/container.tsx",
  command: "src/ui/command/command.tsx",
  "context-menu": "src/ui/context-menu/context-menu.tsx",
  dialog: "src/ui/dialog/dialog.tsx",
  drawer: "src/ui/drawer/drawer.tsx",
  "dropdown-menu": "src/ui/dropdown-menu/dropdown-menu.tsx",
  dropzone: "src/ui/dropzone/dropzone.tsx",
  "emoji-picker": "src/ui/emoji-picker/emoji-picker.tsx",
  empty: "src/ui/empty/empty.tsx",
  "form-field": "src/ui/form-field/form-field.tsx",
  input: "src/ui/input/input.tsx",
  "input-group": "src/ui/input-group/input-group.tsx",
  "input-otp": "src/ui/input-otp/input-otp.tsx",
  item: "src/ui/item/item.tsx",
  kbd: "src/ui/kbd/kbd.tsx",
  label: "src/ui/label/label.tsx",
  marquee: "src/ui/marquee/marquee.tsx",
  menubar: "src/ui/menubar/menubar.tsx",
  meter: "src/ui/meter/meter.tsx",
  "navigation-menu": "src/ui/navigation-menu/navigation-menu.tsx",
  "number-field": "src/ui/number-field/number-field.tsx",
  pagination: "src/ui/pagination/pagination.tsx",
  pill: "src/ui/pill/pill.tsx",
  popover: "src/ui/popover/popover.tsx",
  "preview-card": "src/ui/preview-card/preview-card.tsx",
  portal: "src/ui/portal/portal.tsx",
  progress: "src/ui/progress/progress.tsx",
  "qr-code": "src/ui/qr-code/qr-code.tsx",
  "radio-group": "src/ui/radio-group/radio-group.tsx",
  rating: "src/ui/rating/rating.tsx",
  resizable: "src/ui/resizable/resizable.tsx",
  "scroll-area": "src/ui/scroll-area/scroll-area.tsx",
  select: "src/ui/select/select.tsx",
  separator: "src/ui/separator/separator.tsx",
  sheet: "src/ui/sheet/sheet.tsx",
  sidebar: "src/ui/sidebar/sidebar.tsx",
  skeleton: "src/ui/skeleton/skeleton.tsx",
  slider: "src/ui/slider/slider.tsx",
  spacer: "src/ui/spacer/spacer.tsx",
  spinner: "src/ui/spinner/spinner.tsx",
  switch: "src/ui/switch/switch.tsx",
  table: "src/ui/table/table.tsx",
  tabs: "src/ui/tabs/tabs.tsx",
  textarea: "src/ui/textarea/textarea.tsx",
  "theme-icon": "src/ui/theme-icon/theme-icon.tsx",
  timeline: "src/ui/timeline/timeline.tsx",
  toggle: "src/ui/toggle/toggle.tsx",
  "toggle-group": "src/ui/toggle-group/toggle-group.tsx",
  toolbar: "src/ui/toolbar/toolbar.tsx",
  tooltip: "src/ui/tooltip/tooltip.tsx",
  typography: "src/ui/typography/typography.tsx",
};

export default defineConfig({
  entry: entries,
  format: ["esm"],
  dts: {
    sourcemap: true,
  },
  sourcemap: true,
  clean: true,
  platform: "neutral",
  publint: true,
  attw: {
    profile: "esm-only",
    ignoreRules: ["no-resolution"],
  },
});
